[package]
name = "sdl2_01"
version = "0.12.0"
edition = "2021"
authors = ["The imgui-rs Developers"]
description = "sdl2 support code for the imgui crate"
homepage = "https://github.com/imgui-rs/imgui-rs"
repository = "https://github.com/imgui-rs/imgui-rs"
documentation = "https://docs.rs/imgui-sdl2-support"
license = "MIT OR Apache-2.0"
categories = ["gui"]

[target]

[dependencies]
imgui = {version="0.12.0"}
sdl2 = "0.36"

[dev-dependencies]
glow = "0.13.1"
imgui-glow-renderer = "0.12.0"
sdl2 = { version = "0.36", features = ["bundled", "static-link"] }
